"""
llm_shield.audit
=================
Structured append-only audit logger.

Every request that passes through the pipeline gets an ``AuditEvent`` entry
written to ``logs/audit.jsonl`` (configurable via ``RBACSettings.audit_log_path``).
The file is JSON Lines format — one JSON object per line — so it can be
streamed into any log aggregator (Splunk, Datadog, CloudWatch, etc.).

Schema per entry
----------------
{
  "ts":           "2024-09-01T12:34:56.789Z",  // ISO-8601 UTC
  "event_id":     "uuid4",
  "request_id":   "caller-supplied or generated",
  "user_id":      "...",
  "role":         "guest|user|admin",
  "session_id":   "...",
  "outcome":      "allowed|blocked|error",
  "layer":        "input|prompt|tool|rbac|pipeline",
  "action":       "human-readable description",
  "tool_name":    "...",       // null if not a tool event
  "error_code":   "...",       // null if outcome == allowed
  "error_detail": "...",
  "latency_ms":   123.4,
  "metadata":     {}
}

Public API
----------
``AuditLogger``          — stateful logger; instantiated once in ``rbac.py``.
``AuditEvent``           — dataclass; build one and pass to ``AuditLogger.log``.
``Outcome``              — enum: ``allowed``, ``blocked``, ``error``.
``Layer``                — enum: ``input``, ``prompt``, ``tool``, ``rbac``, ``pipeline``.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class Outcome(str, Enum):
    allowed = "allowed"
    blocked = "blocked"
    error   = "error"


class Layer(str, Enum):
    input    = "input"
    prompt   = "prompt"
    tool     = "tool"
    rbac     = "rbac"
    pipeline = "pipeline"


# ---------------------------------------------------------------------------
# AuditEvent
# ---------------------------------------------------------------------------


@dataclass
class AuditEvent:
    """
    Immutable audit record for a single pipeline action.

    Build one per significant event; pass it to ``AuditLogger.log``.

    Attributes
    ----------
    user_id:      Caller identity string.
    role:         RBAC role at the time of the event.
    outcome:      ``Outcome.allowed`` / ``blocked`` / ``error``.
    layer:        Which pipeline layer generated this event.
    action:       Human-readable description (e.g. ``"tool_invoke:read_file"``).
    session_id:   Correlation ID forwarded from ``UserInput``.
    request_id:   Per-request UUID generated by the pipeline.
    tool_name:    Set for tool-layer events; ``None`` otherwise.
    error_code:   ``LLMShieldError.code`` or ``None``.
    error_detail: Full error message or ``None``.
    latency_ms:   Duration of the event's main operation.
    metadata:     Arbitrary extra context (keep small — ends up in the log).
    """

    user_id:      str
    role:         str
    outcome:      Outcome
    layer:        Layer
    action:       str
    session_id:   str | None       = None
    request_id:   str              = field(default_factory=lambda: str(uuid.uuid4()))
    tool_name:    str | None       = None
    error_code:   str | None       = None
    error_detail: str | None       = None
    latency_ms:   float            = 0.0
    metadata:     dict[str, Any]   = field(default_factory=dict)
    # Timestamp is set at log-write time, not at event construction
    ts: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["outcome"] = self.outcome.value
        d["layer"]   = self.layer.value
        return d


# ---------------------------------------------------------------------------
# AuditLogger
# ---------------------------------------------------------------------------


class AuditLogger:
    """
    Append-only JSON-Lines audit logger.

    Thread-safe for single-writer workloads (file append is atomic on
    POSIX for writes < PIPE_BUF ≈ 4 KB; for multi-process or high-throughput
    production use, replace with a queue-backed async logger).

    Parameters
    ----------
    log_path:  Path to the ``.jsonl`` file (created with parents if absent).
    enabled:   If ``False``, ``log()`` is a no-op (useful in tests).
    """

    def __init__(self, log_path: Path, enabled: bool = True) -> None:
        self._path = log_path
        self._enabled = enabled
        if enabled:
            log_path.parent.mkdir(parents=True, exist_ok=True)

    def log(self, event: AuditEvent) -> None:
        """Append an ``AuditEvent`` as a single JSON line."""
        if not self._enabled:
            return
        line = json.dumps(event.to_dict(), default=str) + "\n"
        with open(self._path, "a", encoding="utf-8") as fh:
            fh.write(line)

    def read_all(self) -> list[dict[str, Any]]:
        """
        Read and parse all events from the log file.

        Returns an empty list if the file doesn't exist yet.
        Useful for the demo CLI's report view and tests.
        """
        if not self._path.exists():
            return []
        events: list[dict[str, Any]] = []
        with open(self._path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line:
                    try:
                        events.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
        return events

    def tail(self, n: int = 20) -> list[dict[str, Any]]:
        """Return the last ``n`` audit entries."""
        return self.read_all()[-n:]


# ---------------------------------------------------------------------------
# Null logger (for tests that don't want file I/O)
# ---------------------------------------------------------------------------


class NullAuditLogger(AuditLogger):
    """
    Drop-all logger — used in tests where audit file I/O is not desired.

    Pass ``NullAuditLogger()`` to ``RBACController(audit_logger=...)``
    to suppress all disk writes in the test suite.
    """

    def __init__(self) -> None:
        super().__init__(log_path=Path("/dev/null"), enabled=False)
        self._events: list[AuditEvent] = []

    def log(self, event: AuditEvent) -> None:
        """Store events in-memory for test assertion."""
        self._events.append(event)

    def logged_events(self) -> list[AuditEvent]:
        """Return all in-memory audit events (for test assertions)."""
        return list(self._events)

    def read_all(self) -> list[dict[str, Any]]:
        return [e.to_dict() for e in self._events]